### ISSUE TITLE
Error 429: Too many requests

### ISSUE THREAD

**Issue by mahrsbar** [ProgramEquity/amplify-front-end#62]
Receiving this error as soon as I search postal code (so after you click on a campaign, and search for a postal code). This means that nothing is loading as it times me out from the api as seen in the screenshot below. 
<img width="704" alt="Screen Shot 2022-01-18 at 5 17 01 PM" src="https://user-images.githubusercontent.com/66452376/150042283-19431e29-e1a1-4071-b22d-1af572a64b65.png">

<img width="725" alt="Screen Shot 2022-01-18 at 5 44 08 PM" src="https://user-images.githubusercontent.com/66452376/150042305-05caac4a-c141-4fd0-9605-fad57036a770.png">

**I think the issue is the following code as it keeps sending requests to API which then makes it time out (I could be wrong). We also need to update this to send the whole member object, not just the name.**
```
        async handleRepClick (member) {
            try{
                this.repName = `Dear ${member.name}`;
                this.shouldRender = false;
                //from campaign id find template id and then make get request with template id
                var campaignId =this.$route.params.campaignId;

                const versions = await axios.get(
                    'https://murmuring-headland-63935.herokuapp.com/api/Letter_Versions/'+ campaignId
                    );

                let latestVersion = versions.data[versions.data.length - 1].template_id;


                const letter = await axios.get(
                    'https://murmuring-headland-63935.herokuapp.com/api/lob/templates/' + latestVersion
                    );
                this.letterBody = letter.data.versions[0].html;
                this.isStep2 = true;


            } catch(e){
                console.error(e);
            }

        },
```

**Comment by nawazkhan** [comment]
@mahrsbar I have updated the rate limit for now which should allow you to proceed with dev work. But, looks like we are making a lot of calls for each rep even before on click.
